# Add this file to your deployed app's secrets in Streamlit Cloud
OPENAI_API_KEY = "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"
NEWS_API_KEY = "9ec01c49764b48708c6b3bc27ac66bb7"